apiVersion: apps/v1
kind: deployment
metadata:
  name: devops-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-training
  template:
    metadata:
    labels:
       app: devops-training
    spec:
      containers:
      - name: devops-training
        image: 
        command: ["/bin/sh"]
        args: ["-c", "sh/usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10; done"]
        ports:
           - name: http
             containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: devops-training-app-service
  labels:
    app: devops-training
spec:
  type: nodePort
  ports:
  - port: 8081
    nodePort: 31500
    protocol: TCP
    name: http
  selector:
    app: devops-training
---
