apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  db_url: mysql-service.database
---

apiVersion: v1
kind: Namespace
metadata:
    name: my-namespace
    labels:
      name: my-namespace
---
apiVersion: v1
kind: Namespace
metadata:
    name: ingress-nginx
    labels:
      name: ingress-nginx
---
